### ISSUE TITLE
Releases to NPM and stability

### ISSUE THREAD

**Issue by folex** [balancer-labs/balancer-v2-monorepo#1241]
Hi! Thank you for your awesome work!

I see that there are releases on NPM
- https://www.npmjs.com/package/@balancer-labs/v2-deployments
- https://www.npmjs.com/package/@balancer-labs/v2-pool-stable

and so on.

But it seems they have been updated 7 months ago, and there have been a lot of updates since then. So I have a few questions:
1. Do you plan to push releases to npmjs.com? 
2. If not, do you have another package repo where you push releases?
3. If I use your smart contracts directly from GitHub repo, how to tell which version/commit to consider stable?

Thanks in advance!

**Comment by nventuro** [comment]
We are aware of our packages being quite outdated - we're planning on revamping all of that during the next month or so and establish processes to make sure users can properly set up our code as dependencies for their projects. This is a bit trickier than it might seem at a first glance, specially given considerations to what 'stable' means in this context.

What the best path for you might be depends on what you're trying to achive. If you want to say develop a new Pool based on existing code, then likely the best approach would be to simply use our repo. I'd pin a recent commit instead of simply using `master`, as things might change as we do internal work, and you'd have to deal with compatibility issues.

Alternatively, if you want to work on top of code already deployed (e.g. interacting with live Pools), then you'll find ABIs and addresses in the deployments package. Accessing old source code (the one used for a given deployment) can be done by either loading the build-info of said deployment, or checking out an old commit.

I know my answer is not entirely satisfactory: we're trying to improve these things but the combination of immutable contracts and new developments make this a bit challenging. If you have any suggestions on what might work better for you, we'd be glad to hear them! In fact, any feedback you might have, including expanding a bit on what task you're trying to achieve, would be extremely helpful to us in being better at this.

Thanks a lot!

**Comment by nventuro** [comment]
The situation has unfortunately not changed much since my last message. 

Could you expand on what you're trying to achieve? That way we'd be able to guide you towards the best way of doing it.

Thanks!

**Comment by nventuro** [comment]
That is unfortunately not an easy task as it might seem - the Balancer protocol is composed is composed of a very large amount (>50) types of deployed contracts, developed over 2+ years. Depending on what it is you want to change that can be done in a number of different ways.

In general, you can look at the files in the `build-info` directory of each [deployment task](https://github.com/balancer-labs/balancer-v2-monorepo/tree/master/pkg/deployments), where you'll find the full source code of the project at the moment that deployment was created, which is the best way to guarantee you're getting the exact same version (though that'll require create source files out of a JSON file, but that should not be a big problem).

**Comment by nventuro** [comment]
We've started the process of updating our releases: [`interfaces`](https://www.npmjs.com/package/@balancer-labs/v2-interfaces) and [`deployments`](https://www.npmjs.com/package/@balancer-labs/v2-deployments) (arguably the most important packages) have both been updated.

We'll continue with some of the more library-like packages, and finally Pools, though how those will be used is still being discussed.
