### ISSUE TITLE
Review / Upgrade dependencies

### ISSUE THREAD

**Issue by EndymionJkb** [balancer-labs/balancer-v2-monorepo#1957]
From the ToB audit, our dependencies are out of date. In particular, the Node version might be different locally vs on CI.

**Comment by jubeira** [comment]
One more thing regarding node versions in CI: we are using `ubuntu-latest` image, which [maps to Ubuntu 20.04](https://github.com/actions/runner-images#available-images) for the time being.

It will be updated to Ubuntu 22.04 soon, but it will still have Node 14 preinstalled. Since we are specifying `node-version: 14` in our setup, the Node version in CI will be 14.20.1 as it is today. See [here](https://github.com/actions/runner-images/issues/6399) for reference.
