### ISSUE TITLE
MultiDistributor: Re-think claim and exit with callbacks

### ISSUE THREAD

**Issue by facuspagnuolo** [balancer-labs/balancer-v2-monorepo#973]
Currently these only work with rewards tokens, stake tokens still depends on users' interactions. This means that even if we have a callback contract, these won't be able to control the staking tokens of the user unless the user had approved them beforehand to do so.

**Comment by nventuro** [comment]
We also need to add a `recipient` field to these.

**Comment by nventuro** [comment]
`claim` and friends should also either:
 * have an explicit `amount` field (not ideal as the claimable amount constantly increases, and why would the full amount not be claimed?), or
 * return the amounts claimed for each token

Otherwise, chaining this operations becomes difficult. See the troubles we went through in https://github.com/balancer-labs/balancer-v2-monorepo/pull/975 due to `joinPool` and `exitPool` not providing this information.

**Comment by TomAFrench** [comment]
> `claim` and friends should also... return the amounts claimed for each token

With #1004 we could add this relatively easily.

**Comment by nventuro** [comment]
Closing as the milestone itself is being closed.
